resourcePackages:
  - webservices
openAPI:
  info:
    title: API Gestion Enseignement
    version: "1.0"
  servers:
    - url: /Gestion_UE_VF_war_exploded
      description: Serveur Local (Développement)